// sample-config.js
module.exports = {
    'applications': [{
        'name': 'app',
        'mode': 'fork',
        'ready-on': 'message',
        'stop-signal': 'message',
        'run': './../apps/sample-app.js',
        'start-timeout': 2000,
        'stop-timeout': 2000,
        'restart-crashing-delay': 300,
        'instances': 3,
    }, {
        'name': 'app-uniform',
        'mode': 'fork',
        'ready-on': 'message',
        'stop-signal': 'message',
        'run': './../apps/sample-app.js',
        'instances': 3,
        'unique-instances': false
    }, {
        'name': 'app-listen',
        'args': ['listen'],
        'mode': 'fork',
        'ready-on': 'instant', // Can't use 'listen' in fork mode
        'stop-signal': 'message',
        'run': './../apps/sample-app.js',
    }, {
        'name': 'app-message',
        'mode': 'fork',
        'ready-on': 'message',
        'stop-signal': 'message',
        'run': './../apps/sample-app.js',
    }, {
        'name': 'app-disconnect',
        'mode': 'fork',
        'ready-on': 'message',
        'stop-signal': 'disconnect',
        'run': './../apps/sample-app.js',
    }, {
        'name': 'app-instant',
        'mode': 'fork',
        'ready-on': 'instant',
        'stop-signal': 'message',
        'run': './../apps/sample-app.js',
    }, {
        'name': 'crashingApp',
        'mode': 'fork',
        'ready-on': 'message',
        'stop-signal': 'message',
        'run': './../apps/crashing-app.js',
    }, {
        'name': 'neverStarts',
        'ready-on': 'message',
        'mode': 'fork',
        'max-instances': 2,
        'start-timeout': 3000,
        'run': './../apps/never-starting-app.js',
    }, {
        'name': 'neverStops',
        'mode': 'fork',
        'ready-on': 'message',
        'stop-timeout': 3000,
        'run': './../apps/never-stopping-app.js',
    }, {
        'name': 'neverStartsFast',
        'ready-on': 'message',
        'mode': 'fork',
        'start-timeout': 10,
        'run': './../apps/never-starting-app.js',
    }, {
        'name': 'neverStopsFast',
        'mode': 'fork',
        'ready-on': 'message',
        'stop-timeout': 10,
        'run': './../apps/never-stopping-app.js',
    }, {
        'name': 'zombie',
        'mode': 'fork',
        'ready-on': 'message',
        'run': './../apps/zombie.js',
        'kill-signal': 'SIGTERM',
        'start-timeout': 500 // immediately become a zombie
    }]
};
